/**
 * Minimal stub for astro:content — used only in the Vitest unit-test environment.
 *
 * The real `astro:content` virtual module is generated by Astro at build time
 * and is not available to Vitest.  This stub provides just enough of the
 * module's surface area to satisfy imports in source files under test.
 *
 * If you add a new import from `astro:content` to a source file, extend this
 * stub accordingly.
 */

import { vi } from "vitest";
import type { CollectionEntry } from "astro:content";

export const getCollection = vi.fn().mockResolvedValue([]);

export const getEntry = vi.fn().mockResolvedValue(undefined);

export const render = vi.fn().mockResolvedValue({
  Content: () => null,
  headings: [],
  remarkPluginFrontmatter: {},
});

// Re-export the `CollectionEntry` type so type-importing files work.
export type { CollectionEntry };
